version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: flauc/firebase
    environment:
      NPM_VERSION: "6.9.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
          name: Install Shared dependencies
          command: npm ci
      - run:
          name: Install Client dependencies
          command: npm --prerfix client ci
      - run:
          name: Install Function dependencies
          command: npm --prerfix functions ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - node_modules
            - client/node_modules
            - functions/node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package-lock.json
            - firebase.json
  deploy:
    docker:
      - image: flauc/firebase
    working_directory: ~/project
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy Master to Firebase
          command: npm run deploy  -- -m "{{ .Environment.CIRCLE_SHA1 }}" --token {{ .Environment.GLOBAL.FIREBASE_CI_TOKEN }}

workflows:
  version: 2
  -deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
